esphome:
  name: create-wind-fan
  friendly_name: Create Wind Fan ESP32
  on_boot:
    then:
      # Al arrancar, silenciamos el beep por seguridad
      # On boot, mute beep for safety
      - switch.turn_off: beep_silenciar

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Logger: no usar UART0 para evitar interferencias con el bus serie del ventilador
# Logger: do not use UART0 to avoid interference with the fan's serial bus
logger:
  baud_rate: 0

# API (proteger la clave en secrets.yaml)
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# Wi-Fi: usar secretos, mejorar conexión con fast_connect y desactivar power save
# Wi-Fi: use secrets, improve connection with fast_connect and disable power save
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  # Punto de acceso de fallback (solo para emergencia). Protege contraseña en secrets.
  # Fallback access point (emergency only). Protect password in secrets.
  ap:
    ssid: "create-wind-fallback"
    password: !secret ap_password

captive_portal:

# Web UI (opcional)
web_server:
  port: 80

# Sincronización horaria desde Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# UART para comunicación con la placa Tuya (verifica pines en tu placa)
# UART for communication with Tuya board (check pins for your board)
uart:
  tx_pin: GPIO21
  rx_pin: GPIO20 
  baud_rate: 9600
  stop_bits: 1

# Tuya UART bridge
tuya:
  id: tuya_device
  time_id: homeassistant_time

# --- Datapoints conocidos ---
# DP 20 -> light on/off
# DP 23 -> color temperature (0, 500, 1000)
# DP 60 -> fan on/off
# DP 62 -> fan speed (1..6)
# DP 63 -> direction (0/1)
# DP 64 -> timer (NO USAR)
# DP 66 -> beep (on/off)

# Fan Tuya
fan:
  - platform: tuya
    id: fan_device
    name: "Ventilador"
    switch_datapoint: 60
    speed_datapoint: 62
    direction_datapoint: 63
    speed_count: 6
    restore_mode: ALWAYS_OFF

# Luz (tuya)
light:
  - platform: tuya
    id: light_device
    name: "Luz del Ventilador"
    switch_datapoint: 20
    restore_mode: ALWAYS_OFF

# Switch para silenciar beep
switch:
  - platform: tuya
    name: "Silenciar Beep"
    id: beep_silenciar
    switch_datapoint: 66
    restore_mode: ALWAYS_OFF

  - platform: restart
    name: "Reiniciar ESP"

# Sensores — reducir frecuencia para bajar tráfico y carga del ESP
sensor:
  - platform: wifi_signal
    name: "Señal WiFi - Create Wind"
    update_interval: 120s

  - platform: uptime
    name: "Tiempo Activo - Create Wind"
    update_interval: 120s

# Selector de temperatura de la luz
number:
  - platform: tuya
    name: "Color de Luz del Ventilador"
    id: light_color
    number_datapoint: 23
    min_value: 0
    max_value: 1000
    step: 500
    unit_of_measurement: "K"
    mode: slider



# --- Notas / recomendaciones ---
# - Mantén las claves secretas en secrets.yaml: wifi_ssid, wifi_password, api_encryption_key, ota_password, ap_password.
# - Keep secret keys in secrets.yaml: wifi_ssid, wifi_password, api_encryption_key, ota_password, ap_password.
#
# - Si el ventilador no responde tras usar el temporizador interno (DP 64), evita usar ese datapoint: requiere reset con mando RF.
# - If the fan does not respond after using the internal timer (DP 64), avoid that datapoint: requires reset with RF remote.
#
# - Si tienes problemas de señal con el ESP dentro de la carcasa metálica, coloca el ESP fuera (falso techo) o usa repetidor.
# - If you have signal issues with the ESP inside the metal housing, place ESP outside (false ceiling) or use a repeater.

