esphome:
  name: create-wind-fan
  friendly_name: Create Wind Fan ESP32

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Habilitar logs por serie y OTA
logger:

# Habilitar API para integrarse con Home Assistant
api:
  encryption:
    key: !secret api_encryption_key  # <-- Añade tu clave en secrets.yaml

ota:
  - platform: esphome
    password: !secret ota_password  # <-- Añade tu contraseña OTA en secrets.yaml

wifi:
  ssid: !secret wifi_ssid  # <-- Añade el SSID de tu red WiFi en secrets.yaml
  password: !secret wifi_password  # <-- Añade la contraseña de tu red WiFi en secrets.yaml

  ap:
    ssid: "create-wind-fallback"  # <-- Puedes cambiarlo si quieres
    password: !secret ap_password  # <-- Añade la contraseña del AP en secrets.yaml

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600

tuya:
  id: tuya_device
  time_id: homeassistant_time

fan:
  - platform: tuya
    id: fan_device
    name: "Ventilador"
    switch_datapoint: 60
    speed_datapoint: 62
    direction_datapoint: 63
    speed_count: 6
    restore_mode: ALWAYS_OFF

light:
  - platform: tuya
    id: light_device
    name: "Luz del Ventilador"
    switch_datapoint: 20
    restore_mode: ALWAYS_OFF

switch:
  - platform: tuya
    name: "Silenciar Beep"
    id: beep_silenciar
    switch_datapoint: 66

  - platform: restart
    name: "Reiniciar ESP"

sensor:
  - platform: wifi_signal
    name: "Señal WiFi"
    update_interval: 60s

  - platform: uptime
    name: "Tiempo Activo"
    update_interval: 60s

# Selector de color de luz (3 tonos: 0, 500, 1000)
number:
  - platform: tuya
    name: "Color de Luz del Ventilador"
    id: light_color
    number_datapoint: 23
    min_value: 0
    max_value: 1000
    step: 500
    unit_of_measurement: "K"
    mode: slider
